# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'LibraryCollections' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LibraryCollections
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'Moya/RxSwift', '~> 13.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'Firebase/Crashlytics'
  pod "Firebase/Performance"
  pod "Firebase/Analytics"
  pod "Firebase/InAppMessaging"
  pod 'Swifter', '~> 1.4.5'


end
